version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  build:
    docker:
    - image: circleci/golang:1.11
    steps:
    - checkout
    - run:
        name: "Build"
        command: |
          make build
    - run:
        name: "Create a temporary directory for artifacts"
        command: |
          mkdir -p /tmp/artifacts
    - run:
        name: "Run Tests & Coverage"
        command: |
          go test -coverprofile=c.out
          go tool cover -html=c.out -o coverage.html
          mv coverage.html /tmp/artifacts
    - store_artifacts:
        path: /tmp/artifacts
    - codecov/upload:
        file: /tmp/artifacts/coverage.html