// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github_repo.proto

package model // import "github.com/guilhermesteves/github-repos-sort-api/internal/model"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GithubRepo struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName             string   `protobuf:"bytes,2,opt,name=fullName,proto3" json:"fullName,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Homepage             string   `protobuf:"bytes,5,opt,name=homepage,proto3" json:"homepage,omitempty"`
	DefaultBranch        string   `protobuf:"bytes,6,opt,name=defaultBranch,proto3" json:"defaultBranch,omitempty"`
	PushedAt             string   `protobuf:"bytes,7,opt,name=pushedAt,proto3" json:"pushedAt,omitempty"`
	CloneUrl             string   `protobuf:"bytes,8,opt,name=cloneUrl,proto3" json:"cloneUrl,omitempty"`
	HtmlUrl              string   `protobuf:"bytes,9,opt,name=htmlUrl,proto3" json:"htmlUrl,omitempty"`
	Forks                int64    `protobuf:"varint,10,opt,name=forks,proto3" json:"forks,omitempty"`
	Stars                int64    `protobuf:"varint,11,opt,name=stars,proto3" json:"stars,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GithubRepo) Reset()         { *m = GithubRepo{} }
func (m *GithubRepo) String() string { return proto.CompactTextString(m) }
func (*GithubRepo) ProtoMessage()    {}
func (*GithubRepo) Descriptor() ([]byte, []int) {
	return fileDescriptor_github_repo_17abfe22aef439bd, []int{0}
}
func (m *GithubRepo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GithubRepo.Unmarshal(m, b)
}
func (m *GithubRepo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GithubRepo.Marshal(b, m, deterministic)
}
func (dst *GithubRepo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GithubRepo.Merge(dst, src)
}
func (m *GithubRepo) XXX_Size() int {
	return xxx_messageInfo_GithubRepo.Size(m)
}
func (m *GithubRepo) XXX_DiscardUnknown() {
	xxx_messageInfo_GithubRepo.DiscardUnknown(m)
}

var xxx_messageInfo_GithubRepo proto.InternalMessageInfo

func (m *GithubRepo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GithubRepo) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *GithubRepo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GithubRepo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *GithubRepo) GetHomepage() string {
	if m != nil {
		return m.Homepage
	}
	return ""
}

func (m *GithubRepo) GetDefaultBranch() string {
	if m != nil {
		return m.DefaultBranch
	}
	return ""
}

func (m *GithubRepo) GetPushedAt() string {
	if m != nil {
		return m.PushedAt
	}
	return ""
}

func (m *GithubRepo) GetCloneUrl() string {
	if m != nil {
		return m.CloneUrl
	}
	return ""
}

func (m *GithubRepo) GetHtmlUrl() string {
	if m != nil {
		return m.HtmlUrl
	}
	return ""
}

func (m *GithubRepo) GetForks() int64 {
	if m != nil {
		return m.Forks
	}
	return 0
}

func (m *GithubRepo) GetStars() int64 {
	if m != nil {
		return m.Stars
	}
	return 0
}

func init() {
	proto.RegisterType((*GithubRepo)(nil), "GithubRepo")
}

func init() { proto.RegisterFile("github_repo.proto", fileDescriptor_github_repo_17abfe22aef439bd) }

var fileDescriptor_github_repo_17abfe22aef439bd = []byte{
	// 273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xcf, 0x4a, 0xf4, 0x30,
	0x14, 0x47, 0x99, 0xce, 0xff, 0x0c, 0xdf, 0x07, 0x06, 0x17, 0xc1, 0x55, 0x11, 0x17, 0xb3, 0xe9,
	0x74, 0xe1, 0x03, 0xc8, 0xcc, 0xc6, 0x9d, 0x8b, 0x82, 0x1b, 0x37, 0x92, 0x69, 0x6e, 0x9b, 0x60,
	0x92, 0x1b, 0x92, 0xd4, 0xc7, 0xf2, 0x19, 0x25, 0x09, 0x15, 0xdd, 0xf5, 0x9c, 0x53, 0x7e, 0x90,
	0x4b, 0x6e, 0x46, 0x15, 0xe5, 0x74, 0x7d, 0xf7, 0xe0, 0xf0, 0xe4, 0x3c, 0x46, 0xbc, 0xff, 0xaa,
	0x08, 0x79, 0xce, 0xb6, 0x03, 0x87, 0xf4, 0x3f, 0xa9, 0x94, 0x60, 0x8b, 0x7a, 0x71, 0x5c, 0x76,
	0x95, 0x12, 0xf4, 0x8e, 0xec, 0x86, 0x49, 0xeb, 0x17, 0x6e, 0x80, 0x55, 0xf5, 0xe2, 0xb8, 0xef,
	0x7e, 0x98, 0x52, 0xb2, 0xb2, 0xc9, 0x2f, 0xb3, 0xcf, 0xdf, 0xb4, 0x26, 0x07, 0x01, 0xa1, 0xf7,
	0xca, 0x45, 0x85, 0x96, 0xad, 0x72, 0xfa, 0xad, 0xd2, 0xa2, 0x44, 0x03, 0x8e, 0x8f, 0xc0, 0xd6,
	0x65, 0x71, 0x66, 0xfa, 0x40, 0xfe, 0x09, 0x18, 0xf8, 0xa4, 0xe3, 0xc5, 0x73, 0xdb, 0x4b, 0xb6,
	0xc9, 0x3f, 0xfc, 0x95, 0x69, 0xc1, 0x4d, 0x41, 0x82, 0x38, 0x47, 0xb6, 0x2d, 0x0b, 0x33, 0xa7,
	0xd6, 0x6b, 0xb4, 0xf0, 0xea, 0x35, 0xdb, 0x95, 0x36, 0x33, 0x65, 0x64, 0x2b, 0xa3, 0xd1, 0x29,
	0xed, 0x73, 0x9a, 0x91, 0xde, 0x92, 0xf5, 0x80, 0xfe, 0x23, 0x30, 0x92, 0x1f, 0x5e, 0x20, 0xd9,
	0x10, 0xb9, 0x0f, 0xec, 0x50, 0x6c, 0x86, 0xcb, 0xf9, 0xed, 0xa9, 0x5c, 0xf1, 0xd4, 0xa3, 0x69,
	0xc7, 0x49, 0x69, 0x09, 0xde, 0x40, 0x88, 0xf0, 0x09, 0xa1, 0x2d, 0xa9, 0x49, 0x07, 0x0e, 0x4d,
	0x40, 0x1f, 0x1b, 0xee, 0x54, 0xab, 0x6c, 0x04, 0x6f, 0xb9, 0x6e, 0x0d, 0x0a, 0xd0, 0xd7, 0x4d,
	0x3e, 0xfd, 0xe3, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5f, 0x2a, 0x5c, 0xb2, 0x8f, 0x01, 0x00,
	0x00,
}
